backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
collections:
  - label: Projects
    name: projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
        allow_multiple: false
        choose_url: false
      - label: Category
        name: category
        widget: string
      - label: Link
        name: link
        widget: string
        pattern: ['https:\/\/.*', "Link must start with https://"]
        hint: Link must start with 'https://'.
      - label: Link Name
        name: link_name
        widget: string
        hint: If supplied, link appears as [Link Name](https://www.example.com), otherwise, it appears as [https://example.com](https://example.com).
        required: false
      - label: Order
        name: order
        widget: number
        default: 0
        hint: Projects with smaller order number appear first within that category.
      - label: Description
        name: body
        widget: markdown
  - label: Pages
    name: pages
    files:
      - label: Home Page
        name: index
        file: content/pages/index.md
        fields:
          - label: Heading
            name: heading
            widget: string
          - label: Hero Image
            name: image
            widget: image
            allow_multiple: false
            choose_url: false
          - label: Blurb
            name: blurb
            widget: text
          - label: Contact Details
            name: contact
            widget: list
            allow_add: true
            hint: Also appears on CV page.
            fields:
              - label: Contact Type
                name: name
                widget: string
              - label: Contact Detail
                name: number
                widget: string
          - label: Offering
            name: offering
            widget: object
            hint: Also appears on CV page.
            fields:
              - label: Offering Introduction
                name: intro
                widget: string
              - label: Skills
                name: skills
                widget: list
                allow_add: true
                fields:
                  - label: Skill Item
                    name: skill_item
                    widget: string
      - label: CV Page
        name: cv
        file: content/pages/cv.md
        fields:
          - label: Heading
            name: heading
            widget: string
          - label: CV
            name: body
            widget: markdown
      - label: Contact Page
        name: contact
        file: content/pages/contact.md
        fields:
          - label: Heading
            name: heading
            widget: string
          - label: Contact Message
            name: contact_message
            hint: Appears just before contact form.
            widget: text
